#ifndef CNOID_ROBOT_ASSEMBLER_PLUGIN_EXPORTDECL_H
#define CNOID_ROBOT_ASSEMBLER_PLUGIN_EXPORTDECL_H

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLIMPORT
#   define CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLEXPORT
#   define CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_ROBOT_ASSEMBLER_PLUGIN_STATIC
#  define CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLAPI
#  define CNOID_ROBOT_ASSEMBLER_PLUGIN_LOCAL
# else
#  ifdef CnoidRobotAssemblerPlugin_EXPORTS
#   define CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLAPI CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLEXPORT
#  else
#   define CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLAPI CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLIMPORT
#  endif
#  define CNOID_ROBOT_ASSEMBLER_PLUGIN_LOCAL CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLLOCAL
# endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_ROBOT_ASSEMBLER_PLUGIN_DLLAPI

#endif // CNOID_ROBOT_ASSEMBLER_PLUGIN_EXPORTDECL_H
